/***********************************************
 *                                              *
 *     Combined Reducers for main application   *
 *     Generated by ts2redux                    *
 *                                              *
 ***********************************************/
import * as redux from 'redux';
import { AppStateReducer, IAppState } from './AppState';
export interface IState {
  AppState: IAppState;
}
// use reducerObject if you combine reducers manually
// for example when using connected-react-router
export const reducerObject = {
  AppState: AppStateReducer,
};
export const reducers = redux.combineReducers<IState>(reducerObject);
